### ISSUE TITLE
Outlook_ProcessFolder.robot needs formatter update

### ISSUE THREAD

**Issue by kaumaron** [KofaxRPA/Mail#12]
The `Extract date` converter on the the `Extract Column in Data Row` step needs to be updated. The format when loaded is `MM/dd/yy hh:mm a` which doesn't match the given data of 9/30/2019 18:06. It seems the converter should be `MM/dd/yyyy hh:mm` to be consistent with the filter data in the example.

**Comment by TungstenRPA** [comment]
fixed

**Comment by TungstenRPA** [comment]
Andrew,
Thanks for posting this. I fixed it.
David
